apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: cloud-native-deployment
  name: cloud-native-deployment
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: tcp
      path: /actuator/prometheus
      scheme: 'http'
  selector:
    matchLabels:
      app: cloud-native-deployment
  namespaceSelector:
    matchNames:
      - cn202102